Repository Standard-Structure/Standard-Structure, pull requests merged in 2020-05, with the labels that each got.

#3 Create Issue Templates
  .github/ISSUE_TEMPLATE/----framework-request.md
  .github/ISSUE_TEMPLATE/---language-request.md
Labels: community

#6 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: community

#14 Add Flask!
  .gitignore
  README.md
  frameworks/flask/README.md
  frameworks/flask/examples/basic/main.py
  frameworks/flask/examples/basic/static/image.png
  frameworks/flask/examples/basic/static/script.js
  frameworks/flask/examples/basic/static/style.css
  frameworks/flask/examples/basic/templates/index.html
Labels: enhancement, framework

#20 Feature/refactor framework structure
  frameworks/flask/README.md
  frameworks/flask/basic/main.py
  frameworks/flask/basic/static/image.png
  frameworks/flask/basic/static/script.js
  frameworks/flask/basic/static/style.css
  frameworks/flask/basic/templates/index.html
  languages/dart/README.md
  languages/dart/basic/.gitignore
  languages/dart/basic/CHANGELOG.md
  languages/dart/basic/analysis_options.yaml
  languages/dart/basic/bin/main.dart
  languages/dart/basic/lib/basic.dart
  languages/dart/basic/pubspec.yaml
  languages/dart/basic/test/basic_test.dart
Labels: refactor

#23 Add Feature/languages/rust
  README.md
  languages/rust/README.md
  languages/rust/basic/.gitignore
  languages/rust/basic/Cargo.lock
  languages/rust/basic/Cargo.toml
  languages/rust/basic/src/main.rs
Labels: enhancement, language

#26 Feature/frameworks/react/basic
  README.md
  frameworks/react/README.md
  frameworks/react/basic/.gitignore
  frameworks/react/basic/README.md
  frameworks/react/basic/package.json
  frameworks/react/basic/public/favicon.ico
  frameworks/react/basic/public/index.html
  frameworks/react/basic/public/logo192.png
  frameworks/react/basic/public/logo512.png
  frameworks/react/basic/public/manifest.json
  frameworks/react/basic/public/robots.txt
  frameworks/react/basic/src/App.css
  frameworks/react/basic/src/App.js
  frameworks/react/basic/src/App.test.js
  frameworks/react/basic/src/index.css
  frameworks/react/basic/src/index.js
  frameworks/react/basic/src/logo.svg
  frameworks/react/basic/src/setupTests.js
  frameworks/react/basic/yarn.lock
Labels: enhancement, framework

#29 [IGNORE] Testing Twitter
  README.md
Labels: framework

#28 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: community

#35 Create CLI
  .vscode/settings.json
  struct-add/.gitignore
  struct-add/README.md
  struct-add/poetry.lock
  struct-add/pyproject.toml
  struct-add/requirements.txt
  struct-add/struct-add/__main__.py
  struct-add/struct-add/ask.py
  struct-add/struct-add/readme.py
Labels: enhancement

#40 Refactor
  frameworks/deno/README.md
  frameworks/deno/basic/README.md
  frameworks/flask/README.md
  frameworks/flask/basic/README.md
  frameworks/react/README.md
  frameworks/react/basic/README.md
  languages/dart/README.md
  languages/dart/basic/README.md
  languages/rust/README.md
  languages/rust/basic/README.md
Labels: documentation

#45 🔥 Remove greetings.yml
  .github/workflows/greetings.yml
Labels: bug, ci/cd

#55 Contributing updates
  CONTRIBUTING.md
  README.md
  docs/Adding a New Language or Framework.md
  docs/Adding a New Structure.md
  docs/Contributing to Generation CLI.md
Labels: documentation
